= Spendenrichtlinie von radikal:klima

Beschlossen am 9. August 2020 +
Geändert am 23. Januar 2021

== Präambel

radikal:klima distanziert sich von Geschäften zulasten von Menschenrechten, zulasten von menschlichen Lebensgrundlagen und zulasten von Ökosystemen. Die Wirtschafts- und Finanzwelt der Zukunft muss nachhaltig sein und ausgewogen mit unseren globalen Lebensgrundlagen umgehen. Wirtschaftsweisen der Ausbeutung und Extraktion sollen überwunden werden und solche der Kooperation auf Augenhöhe und nachhaltigen Balance an ihre Stelle treten. Als Partei nehmen wir deshalb keine Spenden von juristischen oder natürlichen Personen an, die schädliche, nicht nachhaltige oder menschenunwürdige Geschäfte betreiben, sie finanzieren oder anderweitig von ihnen profitieren. Dies bezieht sich sowohl auf akute Schäden als auch auf Schäden, unter denen künftige Generationen leiden werden.

== Aufgabe der Spendenkommission

Jede Spende ab 1.000 EUR muss auf ihre Herkunft geprüft werden. Es ist genau zu recherchieren, ob hinter Spenden von Einzelpersonen womöglich Unternehmen oder Konzerne stecken, deren wirtschaftliches Handeln radikal:klima ablehnt und deren Ziele mit denen von radikal:klima nicht vereinbar sind. Jede Person, die eine Fördermitgliedschaft beantragt, muss vorher von der Spendenkommission dahingehend überprüft werden, ob die Fördermitgliedschaftsbeiträge aus wirtschaftlichen Geschäften stammen könnten, welche diese Spendenrichtlinie ablehnt.

Der Vorstand ist über jede geprüfte Spende zu informieren, die abgelehnt werden sollte. Die Spendenkommission kann lediglich begründete Empfehlungen an den Vorstand aussprechen, warum eine Spende abgelehnt werden sollte. Der Vorstand ist verpflichtet der Spendenkommission innerhalb von einem Monat zu berichten, ob eine zur Ablehnung empfohlene Spende tatsächlich abgelehnt wurde oder nicht.

Mit dem jährlichen Rechenschaftsbericht des Vorstandes muss die Spendenkommission einen eigenen Bericht darüber vorlegen, welche Empfehlungen an den Vorstand ausgesprochen wurden sowie welche Spenden tatsächlich durch den Vorstand abgelehnt wurden.

Diese Spendenrichtlinie ist im Allgemeinen und anlassbezogen von den Mitgliedern der Spendenkommission im Sinne von radikal:klima weiterzuentwickeln und Änderungen beim Landesparteitag zur Abstimmung zu bringen.

== Richtlinien

Für Spenden ab 1.000 EUR und Fördermitgliedschaftsanträge muss dann eine ablehnende Empfehlung an den Vorstand erfolgen, wenn dahinter eine natürliche oder juristische Person steht, die mittelbar oder unmittelbar

* Geschäfte mit fossilen Energieträgern oder der Nutzung dieser klimaschädlichen Stoffe betreibt
* Geschäfte mit schwer klimaschädlichen Prozessen betreibt, ohne ambitionierten Willen, klimapositiv zu werden (Kompensation von Emissionen nicht mitgerechnet)
** insbesondere ist dies zu prüfen bei Geschäftstätigkeit in den Sektoren: industrialisierte Landwirtschaft und Massentierhaltung, Schwerindustrie, Bergbau, Automobil- und Flugindustrie, Finanzierung klimaschädlicher Projekte
* menschenunwürdige Arbeitsbedingungen fördert oder willentlich duldet
** insbesondere Kinderarbeit, sklavenähnliche Produktionsmethoden
* für schwere Umweltschäden verantwortlich ist oder diese duldet
* Landnutzungsänderung im erheblichen Umfang zulasten von Umwelt und Klima unterstützt oder selbst betreibt
* große Flächen aufkauft und diese damit der lokalen Bevölkerung als Nutzfläche entzieht (sog. Landgrabbing)
* Geschäfte mit dem Verbreiten von offensichtlichen Unwahrheiten oder manipulativen Inhalten macht
