= Finanzordnung von radikal:klima

Beschlossen am 9. August 2020 +
Geändert am 23. Januar 2021

== § 1 Zuständigkeit

Der Person im Amt als Schatzmeister:in obliegt die Verwaltung der Finanzen und die Buchführung.

== § 2 Rechenschaftsbericht des Vorstandes

Die Person im Amt als Schatzmeister:in sorgt für die fristgerechte Vorlage des Rechenschaftsberichts gemäß dem fünften Abschnitt des Parteiengesetzes beim Präsidium des Deutschen Bundestages. Unter der Voraussetzung, dass Gebietsuntergliederungen existieren, legt die Person im Amt als jeweilige Schatzmeister:in zu diesem Zweck bis spätestens zum 31. Mai eines jeden Jahres ihren Rechenschaftsbericht vor.

== § 3 Rechenschaftsbericht der Gebietsuntergliederungen

Gebietsuntergliederungen legen ihren jeweils übergeordneten Gebietsgliederungen jährlich bis zum 31. März Rechenschaft über ihr Vermögen, ihre Einnahmen und ihre Ausgaben nach Maßgabe der Bestimmungen des § 24 Parteiengesetz ab.

== § 4 Höhe Mitgliedsbeitrag

(1):: Der Mitgliedsbeitrag beträgt mindestens 10,00 € pro Monat.
(2):: Die Mitgliedsbeiträge können monatlich, quartalsweise, halbjährlich oder jährlich gezahlt werden.
(3):: Personen, die diesen Betrag aus finanziellen Gründen bspw. aufgrund von Arbeitslosigkeit oder Erstausbildung (Schule/Lehre/Studium) nicht leisten können, können einen reduzierten Mitgliedsbeitrag von mindestens 5,00 € pro Monat beantragen. In finanziell besonders schwierigen Situationen (ALG II, Einkommen unterhalb des Existenzminimums) kann der Mitgliedsbeitrag auch ganz erlassen werden. Der Antrag kann formlos beim Vorstand gestellt werden (z.B. per E-Mail). Der Antrag muss die Höhe des gewünschten Mitgliedsbeitrags enthalten. Der reduzierte Mitgliedsbeitrag wird grundsätzlich monatlich abgebucht. Die Reduzierung bzw. die Freistellung von der Zahlungsverpflichtung gilt für 12 Monate und muss dann neu beantragt werden.
(4):: Bei Eintritt im Laufe eines Jahres ist der anteilige Jahresmitgliedsbeitrag pro Monat zu berechnen. Die Berechnung erfolgt monatsgenau, beginnend mit dem Monat, in dem der Eintritt stattfindet.
(5):: Bereits gezahlte Beiträge werden im Falle eines Parteiaustritts nicht erstattet.
(6):: Der Mitgliedsbeitrag sind an die Landespartei zu entrichten.
(7):: Die Schatzmeister:in erarbeitet Änderungsvorschläge zur Höhe des Mitgliedsbeitrages.

== § 5 Sonderbeitragsverpflichtung für Verordnete und Abgeordnete

(1):: Abgeordnete für radikal:klima im Abgeordnetenhaus von Berlin sind verpflichtet, über den Mitgliedsbeitrag hinaus einen Sonderbeitrag in Höhe von monatlich mindestens 100,00 Euro und maximal 15% der Abgeordnetenentschädigung vor Abzug von Steuern und Abgaben zu leisten. Der maximale Sonderbeitrag in Höhe von monatlich 15% der Abgeordnetenentschädigung vor Abzug von Steuern und Abgaben gilt für alle Abgeordneten, sofern Sie nicht nachfolgende Minderungsgründe geltend machen können:
(a)::: Abgeordnete von radikal:klima mit Kindern unter 18 Jahre sind berechtigt den maximalen Sonderbeitrag um 300,00 Euro für jedes unterhaltsberechtigte Kind unter 18 Jahre zu mindern. Der Mindestbetrag von 100,00 Euro Sonderbeitrag monatlich gilt weiterhin.
(b)::: Abgeordnete von radikal:klima mit Kindern ab 18 Jahre, die eine allgemeinbildende Schule besuchen, sich in schulischer Ausbildung befinden oder studieren, sind berechtigt den maximalen Sonderbeitrag um 200,00 Euro pro Kind, das diese Bedingungen erfüllt, zu mindern. Schulbesuch und/oder Studium sind durch entsprechende Nachweise der Bildungseinrichtungen zu belegen. Der Mindestbetrag von 100,00 Euro Sonderbeitrag monatlich gilt weiterhin.
(c)::: Besondere persönliche Umstände (z.B. die Unterstützung pflegebedürftiger Angehöriger, finanzielle Verpflichtungen aus Zeit vor der Abgeordnetentätigkeit u.ä.) können Gründe für individuelle Nachlässe auf den maximalen Sonderbeitrag sein, über die ein dreiköpfiger Entgeltrat entscheidet. Der Entgeltrat wird auf einem Parteitag durch Wahl bestimmt, sobald radikal:klima bei zukünftigen Wahlen Mandate erhält. Sonderbeiträge müssen rückwirkend entrichtet werden.
(2):: Verordnete von radikal:klima in Berliner Bezirksverordnetenversammlungen sind verpflichtet, über den Mitgliedsbeitrag hinaus einen Sonderbeitrag in Höhe von monatlich mindestens 50,00 Euro und maximal 10% der Verordnetenentschädigung vor Abzug von Steuern und Abgaben zu leisten. Der maximale Sonderbeitrag in Höhe von monatlich 10% der Verordnetenentschädigung vor Abzug von Steuern und Abgaben gilt für alle Verordneten, sofern Sie nicht nachfolgende Minderungsgründe geltend machen können:
(a)::: Verordnete von radikal:klima mit unterhaltsberechtigten Kindern unter 18 Jahre zahlen lediglich den Mindestbeitrag von 50,00 Euro.
(b)::: Verordnete von radikal:klima mit Kindern ab 18 Jahre, die eine allgemeinbildende Schule besuchen, sich in schulischer Ausbildung befinden oder studieren zahlen lediglich den Mindestbeitrag von 50,00 Euro. Schulbesuch und/oder Studium sind durch entsprechende Nachweise der Bildungseinrichtungen zu belegen.
(c)::: Besondere persönliche Umstände (z.B. die Unterstützung pflegebedürftiger Angehöriger, finanzielle Verpflichtungen aus Zeit vor der Abgeordnetentätigkeit u.ä.) können Gründe für individuelle Nachlässe auf den maximalen Sonderbeitrag sein, über die der dreiköpfige Entgeltrat aus §5 Absatz 1 Buchstabe c entscheidet.

== § 6 Aufteilung des Mitgliedsbeitrages auf Landes- und Untergliederungsebene

(1):: Die Landespartei erhält alle Mitgliedsbeiträge und sonstigen finanziellen und dinglichen Einnahmen.
(2):: Soweit eine Gebietsuntergliederung besteht, erhält diese 50% der Mitgliedsbeiträge ihrer Mitglieder.
(3):: Die Aufteilung innerhalb einer Gebietsuntergliederung wird von dieser selbst geregelt.
(4):: Der verpflichtende Sonderbeitrag für die mandatstragende Person ist an die Landespartei zu entrichten. 50% gehen an die Gebietsuntergliederung, in der die mandatstragende Person geführt wird.

== § 7 Beitragsabführung

Die den Gebietsuntergliederungen zustehenden Beitragsanteile der eingehenden Mitglieds- und Sonderbeiträge sind quartalsweise abzuführen.

== § 8 Vereinnahmen von Spenden

(1):: Die Landespartei und Gebietsuntergliederungen sind berechtigt, Spenden anzunehmen. Ausgenommen sind Spenden, die nach § 25 Parteiengesetz unzulässig sind. Können unzulässige Spenden nicht zurückgegeben werden, sind diese über die Gebietsuntergliederungen und die Landespartei unverzüglich an das Präsidium des Deutschen Bundestages weiterzuleiten. Eine Spende kann auch durch den Verzicht auf Ersatz von Auslagen geleistet werden. Dies ist auf der Auslagenabrechnung zu vermerken.
(2):: Erbschaften und Vermächtnisse werden ohne Begrenzung angenommen.
(3):: Spendenbescheinigungen werden von der Landespartei ausgestellt.

== § 9 Spendenkommission

(1):: Zur Beurteilung, ob Spendeneingänge mit den Werten und Zielen von radikal:klima vereinbar sind, wird eine unabhängige dreiköpfige Spendenkommission durch den Landesparteitag gewählt.
(2):: Alle Spendeneingänge der Landespartei und der Gebietsuntergliederungen sind dieser Spendenkommission sofort vorzulegen.
(3):: Die Spendenkommission formuliert im Falle einer abzulehnenden Spende eine Empfehlung an den Vorstand, die betreffende Spende abzulehnen.
(4):: Mit dem jährlichen Rechenschaftsbericht des Vorstandes muss die Spendenkommission einen eigenen Bericht darüber vorlegen, welche Empfehlungen an den Vorstand ausgesprochen wurden sowie welche Spenden tatsächlich durch den Vorstand abgelehnt wurden.

== § 10 Veröffentlichung von Spenden

(1):: Spenden derselben Person an die Partei, eine oder mehrere Gebietsuntergliederungen, deren Gesamtwert 10.000 Euro in einem Geschäftsjahr übersteigt, sind im öffentlich zugänglichen Rechenschaftsbericht der Parteigliederung, die sie vereinnahmt hat, zu verzeichnen.

== § 11 Strafvorschrift

Hat eine Gebietsuntergliederung unzulässige, nicht im Rechenschaftsbericht veröffentlichte Spenden vereinnahmt oder sie nach § 8 Absatz 1 nicht an das Präsidium des Deutschen Bundestages weitergeleitet, so verliert sie gemäß § 31a Parteiengesetz den ihr nach der jeweiligen Beschlusslage zustehenden Anspruch auf staatliche Teilfinanzierung in Höhe des zweifachen der rechtswidrig erlangten oder nicht veröffentlichten Spenden.

== § 12 Staatliche Teilfinanzierung

(1):: Die Person im Amt als Schatzmeister:in beantragt jährlich zum 31. Januar für die Landesebene und die Gebietsuntergliederungen die Auszahlung der staatlichen Mittel.
(2):: Über die Verteilung der staatlichen Mittel entscheidet der Landesvorstand in Abstimmung mit den Personen im Amt als Schatzmeister:in in Gebietsuntergliederungen.

== § 13 Haushaltsplan

(1):: Die Person im Amt als Schatzmeister:in stellt für jedes Kalenderjahr bzw. sofort bei Antritt des Amtes einen Haushaltsplan auf, der vom Vorstand beschlossen wird. Ist es absehbar, dass der Haushaltsansatz nicht ausreicht, hat die Person im Amt als Schatzmeister:in unverzüglich einen Nachtragshaushalt einzubringen.
(2):: Die Person im Amt als Schatzmeister:in ist bis zu dessen Verabschiedung an die Grundsätze einer vorläufigen Haushaltsführung gebunden.

== § 14 Zuordnung des Haushalts

Eine Ausgabe, die beschlossen ist, muss durch einen entsprechenden Haushaltstitel auch möglich sein. Beschlüsse, die mit finanziellen Auswirkungen verbunden sind und für deren Deckung kein entsprechender Haushaltstitel vorgesehen ist, sind nur über die Umwidmung von anderen Haushaltstiteln auszuführen.

== § 15 Überschreitung

Wird der genehmigte Haushalt nicht eingehalten, dann muss der Haushalt des Folgejahres durch Veranschlagung oder über eine Haushaltssperre um denselben Betrag bei den Ausgaben reduziert werden.

== § 16 Erstattungsordnung

Der Landesparteitag kann eine Erstattungsordnung für die Abrechnung von Auslagen beschließen; diese ist als Anhang an die Finanzordnung zu formulieren und wird Teil der Finanzordnung. Die Erstattungsordnung wird jedem Mitglied mit dem Blankoformular zur Abrechnung von Auslagen ausgehändigt. Die Erstattungsordnung muss dem Steuerrecht genügen.
