= Satzung von radikal:klima

Beschlossen am 9. August 2020

== Präambel

Unsere Vision ist ein klimapositives und sozial-gerechtes Berlin, das unsere städtischen Lebensgrundlagen und globalen Ökosysteme achtet und schützt. Die notwendige Klimagerechtigkeit werden wir durchsetzen, indem wir die Bewegung ins Parlament bringen. Zu lange schon appellieren wir ohne nennenswerte Folgen an die bestehenden Parteien. Offenbar sind sie zu eingebunden in das fossil betriebene Wachstumssystem und außerstande uns zu retten. Doch die verbleibende Zeit läuft ab, also verlassen wir uns nicht länger auf die alten, verkrusteten Strukturen. Heute nehmen wir unser Schicksal selbst in die Hand und kandidieren, um eine bessere Politik mit wissenschaftlicher Grundlage zu machen. Angetrieben von unseren demokratischen Werten und dem festen Glauben daran, dass wir die Katastrophe noch abwenden können -- jedoch nur mit radikalem gesellschaftlichen Wandel in den nächsten zehn Jahren. Mutig werden wir sein, ehrlich, gewaltfrei und transparent. Nun rufen wir alle Berliner:innen dazu auf sich uns anzuschließen. Gemeinsam mit bestärkten Menschen und Kiezen führen wir unsere Stadt in eine klimapositive Zukunft!

== § 1 Name, Sitz und Tätigkeit

(1):: Die Partei trägt den Namen radikal:klima und die Kurzbezeichnung radikal:klima.
(2):: Der Sitz der Partei ist Berlin.
(3):: Das Tätigkeitsgebiet der Partei ist das Land Berlin.
(4):: Gebietsuntergliederungen tragen den Namen radikal:klima mit dem Zusatz des jeweiligen Gebietsnamens.

== § 2 Aufnahme und Austritt der Mitglieder

=== Voraussetzungen für die Mitgliedschaft

(1):: Mitglied von radikal:klima können alle deutschen Staatsangehörigen und jede Person mit Wohnsitz oder Geburtsort in Deutschland werden. Es gibt kein Mindesteintrittsalter für die Mitgliedschaft. Mitglieder von radikal:klima müssen die Satzung und das Programm der Partei sowie die Gesetze und freiheitliche demokratische Grundordnung in Deutschland anerkennen. Mitglied von radikal:klima können nur natürliche Personen sein.
(2):: Es wird ein zentrales Mitgliederverzeichnis durch den Parteivorstand geführt.
(3):: Personen, die sich um die Mitgliedschaft bei radikal:klima bewerben, ist es nicht gestattet Mitglied einer anderen Partei zu sein. Der Vorstand von radikal:klima kann Ausnahmen von dieser Regel unter Angabe einer klaren Begründung gewähren.
(4):: Personen, die Mitglied einer Organisation sind, die sich gegen die Grundsätze der Partei, gegen die Menschenrechte oder gegen eine demokratische, pluralistische Gesellschaft richtet oder Ziele verfolgt, die gegen diese Grundsätze verstoßen, können nicht Mitglied bei radikal:klima werden. Wenn Mitglieder nach ihrem Eintreten in die Partei einer dieser Organisationen beitreten oder eine bestehende Mitgliedschaft in einer dieser Organisationen nachträglich bekannt wird, ist dies ein zwingender Ausschlussgrund. Es gilt die Unvereinbarkeitsrichtlinie.
(5):: Der Gründungs- und Landesparteitag kann eine Unvereinbarkeitsrichtlinie beschließen, die Näheres regelt und eine Liste mit Organisationen enthält, die als unvereinbar gelten. Der Parteivorstand kann dieser Liste per Beschluss weitere Organisationen hinzufügen und dies durch den folgenden Landesparteitag oder eine Urabstimmung bestätigen lassen.
(6):: Personen, die infolge Richterspruchs die Amtsfähigkeit, die Wählbarkeit oder das Wahlrecht nicht besitzen, können nicht Mitglied von radikal:klima sein bzw. bleiben.

=== Aufnahmeverfahren

(7):: Die Mitgliedschaft wird beim Parteivorstand beantragt. Der Aufnahmeantrag ist in elektronischer oder schriftlicher Form zu stellen. Über die Aufnahme entscheidet der Parteivorstand innerhalb von sechs Wochen nach bestätigtem Eingang des Aufnahmeantrags. Im Falle möglicher Verzögerungen, ist die bewerbende Person schriftlich zu unterrichten. Eine Ablehnung muss nicht begründet werden. Im Mitgliedsantrag muss vollständige Auskunft über aktuelle und frühere Mitgliedschaften in Parteien und sonstigen politischen Gruppierungen gegeben werden.
(8):: Solange es keine Gebietsuntergliederungen gibt, gehört jedes Mitglied der Landespartei an. Unter der Voraussetzung, dass Gebietsuntergliederungen existieren, gehört jedes Mitglied dem Zuständigkeitsgebiet an, in dem es seinen Wohnsitz hat. Bei nachvollziehbaren Gründen, die den Organisationsinteressen nicht entgegenstehen, kann das Mitglied einen Ort seiner Wahl frei bestimmen, anhand dessen seine Mitgliedschaft in Parteigliederungen bestimmt wird. Der entsprechende Antrag erfolgt in Schriftform und wird vom Parteivorstand entschieden. Ein ablehnender Bescheid muss in Schriftform begründet werden und kann im Einspruchsverfahren zur letzten Entscheidung dem zuständigen Schiedsgericht vorgelegt werden.
(9):: Die Mitgliedschaft endet durch Austritt, Ausschluss oder Tod sowie in den Fällen des Absatzes 3. Bereits gezahlte Mitgliedsbeiträge werden nicht erstattet. Der Austritt ist dem Parteivorstand schriftlich anzuzeigen.
(10):: Hat das Mitglied trotz Mahnung einen seit einem Monat fälligen Beitrag nicht bezahlt oder konnte die Lastschrift nicht eingelöst werden, ist das Mitglied schriftlich oder elektronisch erneut zur Zahlung unter Androhung des Ruhens seiner Mitgliedsrechte aufzufordern, falls die Zahlung des angemahnten Beitragsrückstandes nicht binnen eines Monats geleistet werde. Bei Nichtnachkommen der Aufforderung soll das Mitglied schriftlich darauf hingewiesen werden, dass seine Mitgliedsrechte bis zur Bezahlung des Beitragsrückstandes ruhen. Die gerichtliche Geltendmachung der fälligen Mitgliedsbeiträge bleibt hiervon unberührt.

== § 3 Rechte und Pflichten der Mitglieder

(1):: Jedes Mitglied hat das Recht, nach Maßgabe des Gesetzes und im Rahmen dieser Satzung die Zwecke von radikal:klima zu fördern, sich an der politischen Arbeit zu beteiligen und an Veranstaltungen teilzunehmen. Die Mitglieder sind zur Mitarbeit in der Partei aufgerufen. Im Rahmen dieser Mitarbeit haben Mitglieder das Recht an der politischen Willensbildung der Partei durch Aussprachen, eigene Sachanträge, Abstimmungen und Wahlen mitzuwirken.
(2):: Jedes Mitglied hat das Recht, sich an der Erstellung des Programms zu beteiligen und im Rahmen der Gesetze und der Wahlordnung von radikal:klima an der Aufstellung von Wahlvorschlägen und Listen zu beteiligen und/oder selbst dafür zu kandidieren.
(3):: Jedes Mitglied hat das Recht, an Treffen von Arbeitsgruppen teilzunehmen und auch Teil derer zu werden. Die Arbeitsgruppen geben sich eine gemeinsame Geschäftsordnung, die den Rahmen der Zusammenarbeit bestimmt.
(4):: Jedes Mitglied hat die Pflicht, das gemeinsame Grundsatzprogramm anzuerkennen und zu vertreten sowie gemeinsam beschlossene Wahlprogramme und gemeinsam beschlossene Gesetzentwürfe von radikal:klima anzuerkennen und den satzungsgemäßen Mitgliedsbeitrag, welcher in der Finanzordnung geregelt wird, pünktlich zu entrichten.

== § 4 Zulässige Ordnungsmaßnahmen gegen Mitglieder und ihr Ausschluss

(1):: Wenn ein Mitglied gegen die Satzung oder gegen die Grundsätze von radikal:klima verstößt oder dem Ansehen der Partei schadet, aber ein Ausschluss noch nicht in Betracht kommt, kann der Parteivorstand folgende Ordnungsmaßnahmen anordnen: Verwarnung, Verweis, Enthebung von einem Parteiamt, Aberkennung der Fähigkeit ein Parteiamt zu bekleiden und das Ruhen der Mitgliedsrechte für einen begrenzten Zeitraum, der 2 Jahre nicht übersteigen darf.
(2):: Unter der Voraussetzung, dass Gebietsuntergliederungen existieren, werden die Verstöße durch den entsprechenden Vorstand geahndet.
(3):: Ein Mitglied kann nur dann aus der Partei ausgeschlossen werden, wenn es vorsätzlich gegen die Satzung der Partei oder erheblich gegen deren Grundsätze oder Ordnungen verstößt und ihr damit schweren Schaden zufügt.
(4):: Parteischädigendes Verhalten +
 +
Parteischädigend verhält sich insbesondere, wer
(a)::: unvollständige oder unrichtige Auskünfte während des Aufnahmeverfahrens angegeben hat,
(b)::: durch eigene Handlungen oder Aussagen zu einem Vermögensschaden der Partei beiträgt oder diesen herbeiführt,
(c)::: das Ansehen oder die Glaubwürdigkeit der Partei beschädigt,
(d)::: für die Partei spricht ohne hierzu vom jeweiligen Vorstand der Partei (ggf. Parteigebietsuntergliederung) als sprechende Person benannt worden zu sein,
(e)::: einer Organisation gemäß § 2 Absatz 4 oder einer anderen Organisation angehört oder eine solche fördert, deren Ziele nach dem sachlich gerechtfertigten Verständnis der Partei die gleichzeitige Verfolgung der Ziele und Grundsätze der Partei ausschließen, und dadurch die Glaubwürdigkeit und Überzeugungskraft der Partei beeinträchtigt,
(f)::: den eigenen Pflichten als Mitglied beharrlich dadurch nicht nachkommt, dass über einen längeren Zeitraum trotz Zahlungsfähigkeit und trotz Mahnung die persönlichen monatlichen Mitgliedsbeiträge oder etwaige weitere, satzungsrechtlich festgelegte monatliche Beiträge als amts- oder mandatstragende Person der Partei nicht entrichtet,
(g)::: vertrauliche Parteivorgänge veröffentlicht oder Dritten, insbesondere politischen Mitbewerbenden, offenbart,
(h)::: Vermögen, welches der Partei gehört oder zur Verfügung steht, veruntreut.

(5):: Über den Ausschluss entscheidet auf Antrag des zuständigen Vorstandes das nach der Schiedsgerichtsordnung zuständige Schiedsgericht.
(6):: Für Ausschlussverfahren gegen Mitglieder des Parteivorstandes der Partei ist das Schiedsgericht zuständig.
(7):: In dringenden und schwerwiegenden Fällen, die sofortiges Eingreifen erfordern, kann der Parteivorstand ein Mitglied von der Ausübung seiner Rechte bis zur rechtskräftigen Entscheidung des Schiedsgerichts ausschließen. Ein solcher Vorstandsbeschluss gilt gleichzeitig als Antrag auf Einleitung eines Ausschlussverfahrens. Das Schiedsgericht hat in jeder Lage des Verfahrens zu prüfen, ob die Maßnahme nach Umfang und Fortdauer noch erforderlich ist. Soll die Maßnahme über die abschließende Entscheidung einer Schiedsgerichtsinstanz von Gebietsuntergliederungen hinaus wirksam bleiben, so ist sie in dieser Entscheidung erneut anzuordnen; sonst tritt sie mit deren Bekanntmachung außer Kraft.

== § 5 Zulässige Ordnungsmaßnahmen gegen Gebietsverbände

(1):: Folgende Absätze gelten unter der Voraussetzung, dass Gebietsuntergliederungen existieren.
(2):: Verstoßen Gebietsuntergliederungen schwerwiegend gegen die Satzung, die Grundsätze oder die Ordnung von radikal:klima, oder weigert sich begründete Beschwerden aufzugreifen und an ein Schiedsgericht heranzutragen, sind folgende Ordnungsmaßnahmen gegen Gebietsuntergliederungen möglich: Auflösung, Ausschluss, Amtsenthebung von Teilen oder des ganzen Vorstandes nachgeordneter Gebietsverbände.
(3):: Als schwerwiegender Verstoß gegen die Ordnung und die Grundsätze der Partei ist es zu werten, wenn Gebietsuntergliederungen die Bestimmungen der Satzung fortdauernd missachten, Beschlüsse übergeordneter Parteiorgane nicht durchführen oder in wesentlichen Fragen gegen die politische Zielsetzung der Partei handeln.
(4):: Die Ordnungsmaßnahmen werden vom Vorstand der jeweils höheren Gebietsuntergliederungen getroffen. Dessen Mitgliederversammlung hat die Ordnungsmaßnahme am nächsten Parteitag mit einfacher Mehrheit zu bestätigen, ansonsten tritt die Maßnahme außer Kraft. Gegen die Ordnungsmaßnahme ist die Anrufung des nach der Schiedsgerichtsordnung zuständigen Schiedsgerichts möglich.

== § 6 Die allgemeine Gliederung von radikal:klima

(1):: radikal:klima versteht sich als innerhalb Berlins landesweit einheitlich organisierte Partei. Zusätzlich zum Landesverband ist die Gründung von Gebietsuntergliederungen ab 01.11.2020 möglich.
(2):: Gebietsuntergliederungen können nach ihren örtlichen Bedürfnissen die Aufteilung in Bezirks- und Ortsverbände vornehmen.
(3):: Innerhalb der staatsrechtlichen Grenzen Berlins gibt es nur einen Landesverband.
(4):: Bezirks- und Ortsverbände sollen bei Gründung mindestens 5 Mitglieder umfassen. Der Vorstand eines Bezirks- oder Ortsverbandes besteht aus mindestens 3 Personen, wobei mindestens je ein Vorstandsmitglied vorsitzend und eins das Amt als Schatzmeisterin oder Schatzmeister innehaben muss.
(5):: Die Bildung von Gebietsuntergliederungen in Bezirks- und Ortsverbände erfolgt deckungsgleich mit den politischen Grenzen der 12 amtlichen Berliner Bezirke oder deren 96 amtlichen Ortsteile.
(6):: Alle Gebietsuntergliederungen sind an die Satzung, die Wahlordnung, die Finanzordnung und die Schiedsgerichtsordnung des Landesverbandes gebunden.
(7):: Die Gebietsuntergliederungen regeln ihre Angelegenheiten durch eigene Satzung, soweit die Satzung der jeweils nächst höheren Gebietsgliederung hierüber keine Vorschriften enthält. Die Satzungen der Gebietsuntergliederungen können ergänzende Regelungen enthalten, soweit diese der Landessatzung nicht widersprechen. Im Konfliktfall gilt die Landessatzung.
(8):: Organe der Landespartei sind der Parteivorstand und der Landesparteitag.

== § 7 Der Parteivorstand

(1):: Der Parteivorstand wird als "Herzteam" bezeichnet. Er besteht aus Mitgliedern von radikal:klima und vertritt die Landespartei nach innen und außen gemäß § 26 BGB. Der Parteivorstand wird durch mindestens zwei Mitglieder, darunter eine der vorsitzenden Personen oder die amtstragende Person als Schatzmeisterin oder Schatzmeister, gemeinsam gerichtlich und außergerichtlich vertreten. Die Geschäftsführungsbefugnis kann vom Parteivorstand delegiert werden.
(2):: Der Vorstand besteht aus mindestens ebenso vielen Frauen* wie Männern*. Menschen, die sich abseits der binären Konstruktionen verorten, können ungeachtet dessen für jede Position kandidieren.
(3):: Der Parteivorstand leitet den Landesverband, führt dessen Geschäfte nach Gesetz und Satzung und auf der Grundlage der Beschlüsse der Parteiorgane.
(4):: Dem Parteivorstand gehören sechs Mitglieder an:
* fünf vorsitzende Mitglieder
* ein Mitglied im Amt als Schatzmeisterin oder Schatzmeister
(5):: Die Außendarstellung der Partei erfolgt durch den Parteivorstand und von ihm beauftragte oder benannte Personen.
(6):: Die Mitglieder des Parteivorstands werden vom Landesparteitag in geheimer Wahl für die Dauer von zwei Jahren gewählt. Die Wiederwahl ist möglich. Alle Mitglieder des Parteivorstands werden auf demselben Landesparteitag gewählt. Ist eine Nachwahl erforderlich, erfolgt diese nur für den Rest der laufenden Amtszeit. Die Mitglieder des Parteivorstandes führen bis zur Neuwahl des Parteivorstandes die Geschäfte kommissarisch weiter.
(7):: Die Mitglieder des Parteivorstandes können vom Landesparteitag insgesamt oder einzeln mit absoluter Mehrheit abgewählt werden.
(8):: Die Mitglieder des Parteivorstandes dürfen nicht Regierungsmitglied, Abgeordnete oder Mitarbeitende von Fraktionen sowie Abgeordneten sein. Wenn Amtsinhabende Abgeordnetenmandate erhalten, können sie ihr Amt bis zum nächsten Parteitag ausüben. Dieser Parteitag soll zeitnah stattfinden.
(9):: Mitglieder der Partei, die in einem beruflichen oder finanziellen Abhängigkeitsverhältnis zur Landespartei stehen, können kein Parteivorstandsamt bekleiden; Regelungen zur finanziellen Entschädigung des Parteivorstandes bleiben davon unberührt.
(10):: Mitglieder des Parteivorstandes müssen von ihnen ausgeübte unbezahlte Tätigkeiten in Aufsichtsräten, Verbänden und Vereinen gegenüber dem Landesparteitag offenlegen.

== § 8 Der Landesparteitag

(1):: Der Landesparteitag ist die Mitgliederversammlung der Landespartei.
(2):: Der Landesparteitag tagt mindestens einmal jährlich. Die Einberufung erfolgt durch Beschluss des Parteivorstandes oder wenn ein Zehntel der Parteimitglieder es beantragen. Der Parteivorstand lädt jedes Mitglied in Textform (vorrangig per E-Mail, nachrangig per Brief) mindestens 4 Wochen vorher ein. Die Einladung hat Angaben zum Tagungsort, Tagungsbeginn, vorläufiger Tagesordnung und der Angabe, wo weitere, aktuelle Veröffentlichungen gemacht werden, zu enthalten. Spätestens 2 Wochen vor dem Parteitag sind die Tagesordnung in aktueller Fassung, die geplante Tagungsdauer und alle bis dahin dem Vorstand eingereichten Anträge im Wortlaut zu veröffentlichen.
(3):: Ist das Landesgebiet zum Zeitpunkt der Einladung zum Landesparteitag nicht von Gebietsuntergliederungen flächendeckend abgedeckt, tagt der Landesparteitag als Mitgliederversammlung, in der alle Mitglieder stimmberechtigt sind.
(4):: Für den Fall, dass das Landesgebiet zum Zeitpunkt der Einladung zum Landesparteitag von Gebietsuntergliederungen flächendeckend abgedeckt ist, tagt der Landesparteitag als Delegiertenversammlung. Zur Ermittlung der Delegiertenzahl pro Gebietsuntergliederung gilt folgendes Verfahren: Die Zahl der Mitglieder der Gebietsuntergliederung wird mit 50 multipliziert. Das Ergebnis wird durch die Summe der Mitglieder der Landespartei dividiert, wobei das Ergebnis zu einer vollen Zahl gerundet wird. Diese Zahl ist die jeweilige Delegiertenzahl, die aber in jedem Fall mindestens 1 betragen muss (Grundmandat).
(5):: Maßgeblich für die Berechnung der Delegiertenzahlen sind die dem Bundestagspräsidium im letzten Jahresrechenschaftsbericht vorgelegten, geprüften Mitgliederzahlen.
(6):: Mitglieder können bei der Mitgliederversammlung ihr Stimmrecht entweder persönlich oder per Stimmrechtsübertragung wahrnehmen.
(7):: Mitglieder können ihr Stimmrecht mittels einer Vollmacht vorübergehend auf eine andere Person übertragen, sofern sie nicht selbst für den Parteitag akkreditiert sind. Diese Person muss Mitglied der Partei sein. Jedes stimmberechtigte Mitglied kann maximal zwei weitere Mitglieder vertreten. Eine Vollmacht kann nur unmittelbar ausgestellt werden, Untervollmachten sind nicht zulässig. Zum Parteitag muss die Vollmacht schriftlich -- mit einer Kopie des Personalausweises der vollmachtgebenden Person -- für den Erhalt der Stimmkarten vorgezeigt werden. Mitglieder, die aufgrund von Übertragung mehrere Stimmrechte vertreten, müssen diese nicht gleichlautend abgeben.
(8):: Ist der Parteivorstand handlungsunfähig, kann ein außerordentlicher Landesparteitag einberufen werden. Dies geschieht schriftlich mit einer Frist von zwei Wochen unter Angabe der Tagesordnung und des Tagungsortes. Er dient ausschließlich der Wahl eines neuen Vorstandes.
(9):: Aufgaben des Landesparteitages:
(a)::: Der Landesparteitag beschließt über die Grundlinien der Politik von radikal:klima, über das Landesprogramm und die Ausrichtung der Landespartei.
(b)::: Er beschließt über die Satzung, die Finanzordnung und die Schiedsgerichtsordnung.
(c)::: Er beschließt über die Auflösung sowie die Verschmelzung mit anderen Parteien nach § 11.
(d)::: Er wählt die Mitglieder des Parteivorstandes gemäß § 7 Absatz 5.
(e)::: Der Landesparteitag nimmt den Tätigkeitsbericht des Parteivorstandes entgegen und entscheidet daraufhin über seine Entlastung.
(f)::: Er entscheidet entsprechend Absatz 13, ob die Teilnahme der Landespartei an der Wahl zum Deutschen Bundestag, zum Abgeordnetenhaus von Berlin und/oder den einzelnen Bezirksverordnetenversammlungen erfolgt.
(10):: Über den Parteitag, die Beschlüsse und Wahlen wird ein Ergebnisprotokoll gefertigt, das von einem Mitglied der Protokollführung, einem Mitglied der Versammlungsleitung und einer der vier vorsitzenden Personen unterschrieben wird. Wurden die Vorsitzenden neu gewählt, so unterschreiben die neu gewählten Vorsitzenden. Das Wahlprotokoll wird dem Protokoll beigefügt.
(11):: Der Landesparteitag wählt mindestens zwei Kassenprüfende, die nicht Mitglieder des Parteivorstands sein dürfen. Diesen obliegen die Vorprüfung des finanziellen Tätigkeitsberichtes für den folgenden Landesparteitag und die Vorprüfung, ob die Finanzordnung und das Parteiengesetz eingehalten werden. Sie haben das Recht, kurzfristig Einsicht in alle finanzrelevanten Unterlagen zu verlangen, die ihnen dann vollständig zu übergeben sind. Sie sind angehalten, etwa zwei Wochen vor dem Landesparteitag die letzte Vorprüfung der Finanzen durchzuführen. Die Amtszeit der Kassenprüfenden ist deckungsgleich mit der Amtszeit der Mitglieder des Parteivorstandes.
(12):: Der Landesparteitag gibt sich eine Geschäftsordnung. Sollten einzelne Bestimmungen der Geschäftsordnung ganz oder teilweise der Satzung widersprechen, so hat die Satzung Vorrang. Die Wirksamkeit der übrigen Geschäftsordnung wird dadurch nicht berührt.
(13):: Die Beschlüsse des Landesparteitags werden mit einfacher Mehrheit der abgegebenen gültigen Stimmen getroffen, sofern keine abweichenden Regelungen in der Wahlordnung getroffen sind. Bei Stimmengleichheit gilt ein Antrag als abgelehnt. Stimmenthaltungen können gezählt werden, werden jedoch weder als gültige noch als ungültige Stimmen gewertet und bleiben daher unberücksichtigt.
(14):: Beschlüsse außerhalb von Satzungsänderungen, egal ob angenommen oder abgelehnt, müssen spätestens zwei Monate nach Annahme vorliegen. Diese müssen allen Mitgliedern schriftlich oder elektronisch kommuniziert und im Online-Auftritt veröffentlicht werden. Die Verantwortliche Stelle für die Um- und Durchsetzung ist der Parteivorstand, der diese Aufgabe zwar delegieren kann, aber letztendlich verantwortlich bleibt. In begründeten Ausnahmefällen kann der Parteivorstand die Kommunikation und Veröffentlichung der Beschlüsse um einen weiteren Monat auf dann insgesamt drei Monate nach dem Beschluss über Satzungsänderungen verschieben.

== § 9 Einrichtung von Wahlvorschlägen

(1):: Für die Aufstellung der sich Bewerbenden für Wahlen zu Volksvertretungen gelten die Bestimmungen der Wahlgesetze und der Satzungen der Landespartei. Näheres regelt die Wahlordnung, die Bestandteil der Satzung ist und Satzungsrang hat.

== § 10 Urabstimmung

(1):: Über alle Fragen der Politik der Partei, insbesondere auch des Programms, kann urabgestimmt werden. Stimmberechtigt sind alle Mitglieder der Partei.
(2):: Die Urabstimmung findet statt auf Antrag
(a)::: von zehn von Hundert der Mitglieder, wobei diejenigen Mitglieder nicht berücksichtigt werden, die zum Zeitpunkt der Antragstellung mit ihren Mitgliedsbeiträgen im Rückstand sind, oder
(b)::: von drei Gebietsuntergliederungen oder
(c)::: des Landesparteitages oder
(d)::: des Parteivorstands.
(3):: Die antragstellenden Personen legen durch die Antragsschrift den Inhalt der Urabstimmung fest.
(4):: Der Parteivorstand beauftragt eine Person mit der Durchführung der Urabstimmung.
(5):: Das Nähere wird in Ausführungsbestimmungen geregelt, die der Parteivorstand erlässt.
(6):: Die Kosten der Urabstimmung trägt die Landespartei.
(7):: Der Parteivorstand übernimmt die Aufgabe, alle Parteimitglieder zu informieren (vorrangig per E-Mail, nachrangig per Brief).
(8):: Der Parteivorstand hat das Recht, zusammen mit der beantragten Formulierung einen Alternativantrag zur Abstimmung zu stellen. Die Arbeitsgruppen sind gehalten, zum Thema der jeweiligen Urabstimmung Informationsveranstaltungen durchzuführen. Die Information zur Urabstimmung hat sachdienlich, umfassend und neutral zu sein.
(9):: Ein einmal per Urabstimmung beschlossener Inhalt kann erst nach Ablauf von 2 Jahren erneut Gegenstand eines Urabstimmungsverfahrens sein.
(10):: Wenn eine Urabstimmung zu einem Gegenstand nicht möglich ist, wird eine Mitgliederbefragung zu dem Gegenstand durchgeführt und dem folgenden Parteitag zur Bestätigung vorgelegt.

== § 11 Auflösung und Verschmelzung

(1):: Die Auflösung der Landespartei oder ihre Verschmelzung mit einer anderen Partei kann nur durch einen Beschluss des Landesparteitages mit einer Mehrheit von 3/4 der zum Landesparteitag Stimmberechtigten beschlossen werden.
(2):: Ein Beschluss über Auflösung oder Verschmelzung muss durch eine Urabstimmung unter allen Parteimitgliedern bestätigt werden.
(3):: Über einen Antrag auf Auflösung oder Verschmelzung kann nur abgestimmt werden, wenn er mindestens vier Wochen vor Beginn des Landesparteitages beim Parteivorstand eingegangen ist.

== § 12 Schiedsgerichte

(1):: Auf Landes- und Gebietsuntergliederungsebene sind Schiedsgerichte einzurichten. Zusammensetzung, Zuständigkeit und Verfahren regelt die Schiedsgerichtsordnung. Die Schiedsgerichtsordnung ist Bestandteil der Satzung und hat Satzungsrang.

== § 13 Finanzordnung

(1):: Die Landespartei sowie alle weiteren Gliederungen von radikal:klima sind bezüglich der Aufbringung, Verwendung und Verwaltung von finanziellen Mitteln an die Finanzordnung von radikal:klima gebunden. Die Finanzordnung ist Bestandteil der Satzung und hat Satzungsrang.

== § 14 Änderung der Satzung

(1):: Die Satzung kann durch einfache Mehrheit der Mitglieder geändert werden.
(2):: Soweit die Satzung nichts anderes bestimmt, erhalten Änderungen der Satzung (einschließlich aller ihrer Bestandteile) ihre Gültigkeit sofort mit der Verabschiedung auf dem Parteitag.
(3):: Eine oder mehrere Änderungen egal welcher Satzungsdokumente müssen spätestens zwei Monate nach der beschlossenen Änderung in der aktualisierten Fassung vorliegen. Aktualisierte Fassungen müssen allen Mitgliedern schriftlich kommuniziert und im OnlineAuftritt veröffentlicht werden.
(4):: Die Verantwortliche Stelle für die Um- und Durchsetzung ist der Parteivorstand, der diese Aufgabe zwar delegieren kann, aber letztendlich verantwortlich bleibt.
(5):: In begründeten Ausnahmefällen kann der Parteivorstand die Kommunikation und Veröffentlichung der geänderten Satzungsdokumente um einen weiteren Monat auf dann insgesamt drei Monate nach dem Beschluss über Satzungsänderungen verschieben.

== § 15 Salvatorische Klausel

(1):: Sollten einzelne Bestimmungen dieser Satzung ganz oder teilweise unwirksam oder nichtig sein, wird dadurch die Wirksamkeit der übrigen Satzung nicht berührt.
(2):: Bestandteile der Landessatzung sind weiterhin die Wahlordnung, die Finanzordnung und die Schiedsgerichtsordnung.
(3):: Die Satzung tritt mit Beschluss des Gründungsparteitages am 9. August 2020 in Kraft.

== Anhang

(1):: https://www.radikalklima.de/satzungsdokumente/unvereinbarkeitsrichtline[Unvereinbarkeitsrichtlinie]
