= Wahlordnung der Klimaliste Berlin

Beschlossen am 9. August 2020 +
Geändert am 27. März 2021

== § 1 Geltungsbereich

(1):: Diese Wahlordnung gilt für alle Wahlen innerhalb der Partei.
(2):: Sie gilt, vorbehaltlich besonderer Bestimmungen der Wahlgesetze, auch für Versammlungen zur Aufstellung von Wahlbewerbenden für öffentliche Wahlen.

== § 2 Wahlgrundsätze

(1):: Es gilt allgemein der Grundsatz der freien, gleichen und geheimen Wahl.
(2):: Wahlen, die weder die Besetzung von Organen der Partei oder ihrer Gebietsuntergliederungen, noch mittelbar (Wahl von Vertretenden) oder unmittelbar die Aufstellung von Wahlbewerbenden betreffen, können offen durchgeführt werden, wenn keine wahlberechtigten Versammlungsteilnehmenden dem widersprechen.
(3):: Eine Versammlung kann im Rahmen des Grundsatzes nach Absatz 1 und im Rahmen der Satzung ergänzende oder abweichende Bestimmungen zu den §§ 7 und 8 und 10 bis 12 treffen.
(4):: Ein entsprechender Versammlungsbeschluss kann niemals rückwirkend auf eine bereits stattgefundene Wahlhandlung angewendet werden.
(5):: Nach Versammlungsbeschluss sind auch elektronische Wahlen zulässig, soweit diese das Wahlgeheimnis, den Datenschutz und die Manipulations- und Dokumentationssicherheit gewährleisten. Die Bestimmungen dieser Wahlordnung sind dabei entsprechend anzuwenden.
(6):: Eine Versammlung kann Wahlen durchführen, wenn fristgerecht eingeladen wurde oder mindestens drei Viertel der stimmberechtigten Mitglieder anwesend sind.

== § 3 Ankündigungen von Wahlen

(1):: Wahlen sind anzusetzen, wenn Neu- oder Nachwahlen satzungsgemäß vorgeschrieben sind oder wenn ein zulässiger Antrag auf die Durchführung von Neu- oder Nachwahlen bzw. ein zulässiger Abwahlantrag vorliegt.
(2):: Sind Wahlen angesetzt, so lädt der Vorstand jedes Mitglied in Textform zur Wahl ein. Die Einladung ist fristgerecht, wenn spätestens 10 Tage vor der Wahl eingeladen wurde. Liegen zwischen der Aufforderung zur Einreichung von Wahlvorschlägen für eine Parlamentswahl und dem Datum der Parlamentswahl weniger als 90 Tage, so ist abweichend hiervon die Einladung zu einer Wahl zur Aufstellung eines Wahlvorschlags für die Parlamentswahl fristgerecht, wenn spätestens 7 Tage vor der Wahl eingeladen wurde. Für die Gründungsveranstaltung gilt keine Frist.

== § 4 Wahlkommission

(1):: Zur Durchführung einer oder mehrerer Wahlen bestimmt die Versammlung in offener Abstimmung eine Wahlkommission, welche mindestens zwei Mitglieder hat und aus ihrer Mitte eine wahlleitende Person bestimmt, sofern diese nicht bereits durch die Versammlung bestimmt wurde.
(2):: Die Wahlkommission leitet die Wahlhandlung und stellt das Wahlergebnis fest.
(3):: Die Mitglieder der Wahlkommission müssen der Versammlung nicht angehören. Die Wahlkommission kann bei Bedarf weitere Wahlhelfende hinzuziehen.
(4):: Wer selbst bei einer der Wahlen kandidiert, kann nicht der Wahlkommission angehören. Erklärt ein Mitglied der Wahlkommission eine Kandidatur, scheidet es unmittelbar aus der Wahlkommission aus.

== § 5 Wahl für unterschiedliche Parteiämter oder Mandate

(1):: Wahlen für unterschiedliche Parteiämter oder Mandate finden in jeweils gesonderten Wahlgängen nacheinander statt. Die Versammlung kann entscheiden, dass Wahlgänge parallel stattfinden können, ausgenommen hiervon sind die für den Vorstand.
(2):: Bei parallel stattfindenden Wahlgängen ist eine gleichzeitige Wahlbewerbung auch dann möglich, wenn die gleichzeitige Annahme der zu wählenden Parteiämter und Mandate ausgeschlossen ist.
(3):: Bei der Aufstellung der einzelnen Listenplätze von Wahlvorschlagslisten für öffentliche Wahlen ist analog zu verfahren.

== § 6 Gemeinsame Wahl gleicher Parteiämter

(1):: Für Wahlen von Parteiämtern kann die Versammlung auf Antrag der Wahlleitung in offener Abstimmung bestimmen, dass die Wahl aller Funktionen, außer die des Vorstandes gemeinsam stattfinden soll.
(2):: Nach der Wahl werden die Kandidierenden, die die erforderliche Mehrheit nach § 10 erreicht haben, nach absteigender Anzahl der Ja-Stimmen geordnet.
(3):: Die am Ende des Verfahrens ausgewählten Kandidierenden sind gewählt.
(4):: Bei Stimmengleichheit ist § 11 Absatz 3 bzw. Absatz 4 anzuwenden.

== § 7 Wahl des Vorstandes

(1):: Die Wahl des Vorstandes beginnt mit der Person im Amt als Schatzmeisterin oder Schatzmeister.
(2):: Danach werden alle Vorsitzenden in einzelnen Wahlgängen gewählt.
(3):: Sobald in den Vorstand so viele Männer gewählt wurden, wie nach § 7 Absatz 2 Satzung möglich sind, dürfen für die verbleibenden Positionen nur noch Frauen kandidieren. Absatz 4 bleibt hiervon unberührt.
(4):: Menschen, die sich weder als Frau noch als Mann identifizieren, können für jede Position kandidieren.
(5):: Wenn § 7 Absatz 2 Satzung nicht erfüllt werden kann, ist die Versammlungsleitung verpflichtet, der Versammlung einen Lösungsvorschlag zu unterbreiten.

== § 8 Wahlvorschläge

(1):: Jedes Parteimitglied kann Wahlvorschläge unterbreiten (nominieren) oder sich selbst bewerben. Für weitere Wahlgänge nach § 12 können nur wahlberechtigte Versammlungsteilnehmende Wahlvorschläge unterbreiten.
(2):: Wahlvorschläge sollten vor der Aufstellungsversammlung schriftlich eingereicht werden, damit sie bekannt gegeben werden können. Das Einverständnis für die Kandidatur ergibt sich für diejenigen, die sich selbst bewerben aus der Kandidatur selbst und muss für vorgeschlagene Personen von den vorgeschlagenen Personen selbstständig erklärt werden (elektronische Übermittlung ist ausreichend).
(3):: Wenn eine vorgeschlagene Person in der Wahlversammlung selbst anwesend ist, kann sowohl der Wahlvorschlag als auch die Zustimmung der beworbenen Person durch Zuruf erfolgen. Auf Zuruf können jedoch nur wahlberechtigte Versammlungsteilnehmende Wahlvorschläge unterbreiten.
(4):: Wahlvorschläge sind bis zum Abschluss der Bewerbenden-Liste für den entsprechenden Wahlgang zulässig.
(5):: Alle vorgeschlagenen und sich selbst Bewerbenden erhalten eine angemessene Redezeit von mindestens 10 Minuten zu ihrer Vorstellung. Über den Umfang von Fragen an und Stellungnahmen zu Bewerbenden entscheidet die Versammlungsleitung, wenn nicht durch Versammlungsbeschluss abweichend geregelt. Dabei sind die Bewerbenden für gleiche Parteiämter oder Mandate gleich zu behandeln.

== § 9 Aufstellung von Wahlvorschlägen

(1):: Listenplätze sind abwechselnd mit Frauen und Männern zu besetzen, wobei der erste Listenplatz einer Frau vorbehalten ist.
(2):: Menschen, die sich weder als Frau noch als Mann identifizieren, können auf jeden Listenplatz kandidieren.

== § 10 Stimmabgabe

(1):: Stimmzettel in einem Wahlgang müssen in Form und Farbe einheitlich sein.
(2):: Jede wahlberechtigte Person hat das Recht, hinter dem Namen jeder sich bewerbenden Person mit Ja oder mit Enthaltung zu stimmen. Fehlt eine Kennzeichnung, gilt dies als Enthaltung.
(3):: Die Zahl der zulässigen Ja-Stimmen in einem Wahlgang ist auf die Zahl der zu besetzenden Parteiämter oder Mandate begrenzt. Die zulässige Zahl der Ja-Stimmen muss bei der Stimmabgabe nicht ausgeschöpft werden.

== § 11 Stimmenauszählung und ungültige Stimmen

(1):: Die Stimmenauszählung durch die Wahlkommission ist parteiöffentlich. Die ordnungsgemäße Auszählung darf durch die Öffentlichkeit nicht beeinträchtigt werden. Bei der Stimmenauszählung ist zu gewährleisten, dass keine Rückschlüsse auf das Wahlverhalten möglich sind.
(2):: Die Wahlkommission hat Stimmzettel für ungültig zu erklären, wenn auf ihnen der Wille der Wählenden nicht gemäß dieser Wahlordnung erkennbar ist, wenn auf ihnen mehr Stimmen als zulässig abgegeben wurden oder wenn sie das Prinzip der geheimen Wahl verletzen.

== § 12 Mehrheitsbegriff

(1):: Grundsätzlich sind in einem Wahlgang diejenigen Personen gewählt, welche die meisten Ja-Stimmen auf sich vereinen (relative Mehrheit).

== § 13 Reihenfolge der Wahl und Verfahren bei Stimmengleichheit

(1):: Bewerben sich in einem Wahlgang mehr Bewerbende als Parteiämter oder Mandate zu besetzen sind, so sind diejenigen Bewerbenden in absteigender Reihenfolge der Ja- Stimmen-Anzahl gewählt, die der Anzahl der zu vergebenden Parteiämter oder Mandate entsprechen.
(2):: Bei Delegiertenwahlen sind alle weiteren Bewerbenden in der Reihenfolge ihrer Ja- Stimmen-Zahl als Ersatzdelegierte gewählt, soweit nicht zur Wahl der Ersatzdelegierten gesonderte Wahlgänge stattfinden.
(3):: Bei gleicher Anzahl zu besetzender Parteiämter oder Mandate und sich Bewerbender, ist eine Stimmengleichheit unschädlich.
(4):: Wenn aber die Anzahl der sich Bewerbenden die Anzahl der zu besetzender Parteiämter oder Mandate übersteigt, ist eine Stichwahl nach §§ 10 bis 11 durchzuführen. Wenn nach erfolgter Stichwahl weiterhin Stimmengleichheit besteht, entscheidet das Los.

== § 14 Weitere Wahlgänge

(1):: Bleiben nach einem Wahlgang Parteiämter oder Mandate unbesetzt, kann durch Versammlungsbeschluss entweder
* die Wahl vertagt oder
* ein weiterer Wahlgang (nach den §§ 5 bis 11) aufgerufen oder
* eine Stichwahl herbeigeführt werden.

== § 15 Annahme der Wahl, Wahlprotokoll und Nachwahlen

(1):: Eine Wahl gilt als angenommen, wenn die gewählte Person dem nicht unmittelbar nach Bekanntgabe des Wahlergebnisses widerspricht.
(2):: Jede Wahl ist zu protokollieren. Das Protokoll muss alle ergänzenden Versammlungsbeschlüsse zu dieser Wahlordnung und alle Wahlergebnisse enthalten. Es ist durch die Wahlleitung und mindestens ein weiteres Mitglied der Wahlkommission zu unterzeichnen. Die Wahlunterlagen (Wahlprotokoll, Stimmzettel, Zählzettel, Wahllisten usw.) sind für die Dauer der Wahlperiode der Gewählten aufzubewahren.
(3):: Vakante Parteiämter sind durch Nachwahlen zu besetzen.
(4):: Vakante Delegiertenmandate sind nur dann durch Nachwahlen zu besetzen, wenn keine gewählten Ersatzdelegierten mehr zur Verfügung stehen.

== § 16 Wahlwiederholung

(1):: Wird während der Wahlhandlung oder während der Stimmenauszählung eine wahlhelfende Person festgestellt, die relevanten Einfluss auf das Wahlergebnis haben kann, hat die Wahlkommission die Wahlhandlung bzw. die Stimmenauszählung sofort abzubrechen und die Wiederholung der Wahlhandlung zu veranlassen. Der Grund für die Wahlwiederholung ist im Wahlprotokoll festzuhalten.
(2):: Im Übrigen kann eine Wahlwiederholung nur infolge einer Wahlanfechtung stattfinden.

== § 17 Wahlanfechtung

(1):: Wahlen können bei dem zuständigen Schiedsgericht angefochten werden, wenn die Verletzung von Bestimmungen dieser Wahlordnung, der Satzung, des Parteiengesetzes, der Wahlgesetze oder des Verfassungsrechts geltend gemacht wird und eine solche Rechtsverletzung zumindest möglich erscheint.
(2):: Wahlanfechtungen haben keine aufschiebende Wirkung.
(3):: Anfechtungsberechtigt sind:
* der Vorstand und die zuständigen Vorstände der Gebietsuntergliederungen
* wahlberechtigte Versammlungsteilnehmende
* alle Wahlbewerbende.
(4):: Eine Wahlanfechtung ist binnen zwei Wochen nach Ablauf des Tages, an dem die Wahl stattfand, zulässig.
(5):: Eine Wahlanfechtung ist nur begründet, wenn und soweit der behauptete Mangel Einfluss auf das Ergebnis der Wahl gehabt haben kann.
(6):: Das Schiedsgericht ist bei einer berechtigten Wahlanfechtung befugt, eine Wahlwiederholung anzuordnen.
