= Schiedsgerichtsordnung von radikal:klima

Beschlossen am 9. August 2020

== § 1 Grundlagen

(1):: Diese Schiedsgerichtsordnung regelt das Verfahren vor den Schiedsgerichten der Landespartei und der Gebietsuntergliederungen.
(2):: Sie ist für alle Mitglieder und Organe der Partei und ihre Gliederungen bindend.

== § 2 Schiedsgerichte

(1):: Auf der Landesebene der Partei wird ein Schiedsgericht eingerichtet. Auf Gebietsuntergliederungen wird bei Gründung ebenfalls jeweils ein Schiedsgericht eingerichtet.
(2):: Die Schiedsgerichte sind unabhängig und an keinerlei Weisungen gebunden.
(3):: Die in ein Schiedsgericht gewählten Personen fällen ihre Entscheidungen nach bestem Wissen und Gewissen auf Grundlage der Satzungen und gesetzlichen Vorgaben.
(4):: Die in ein Schiedsgericht gewählten Personen müssen alle Vorgänge des Schiedsgerichtes vertraulich behandeln. Beeinflussungsversuche hat das Schiedsgericht dem Vorstand des jeweiligen Gebietsverbandes jedoch unverzüglich mitzuteilen.
(5):: Die Schiedsgerichte geben sich jeweils eine Geschäftsordnung. Diese enthält insbesondere Regelungen über
(a)::: die Verwaltungsorganisation,
(b)::: die Vergabe von Aktenzeichen
(c)::: die Dokumentation der Arbeit des Schiedsgerichtes, der Aufbewahrung von Akten und der Akteneinsicht.

== § 3 Wahl von Personen für das Schiedsgericht

(1):: Der jeweilige Gebietsuntergliederungs- oder Landesparteitag wählt drei Parteimitglieder, in das Schiedsgericht, sowie drei Mitglieder als Ersatz für die hauptamtlichen Personen. Die nach der Rangfolge nächste Ersatzperson ist diejenige, die von den dreien die meisten Stimmen auf sich vereinigt. Die drei gewählten Personen im Schiedsgericht wählen wiederum aus ihren Reihen eine vorsitzende Person, die das Schiedsgericht leitet und die Geschäfte führt.
(2):: Die sich zur Wahl aufstellende Person muss nicht Mitglied der Partei sein.
(3):: Die in ein Schiedsgericht gewählten Personen können nicht zugleich ein Amt oder Mandat für die Partei oder einen Gebietsverband bekleiden, in einem Dienstverhältnis zu der Partei oder einer Gebietsuntergliederung stehen oder von ihnen regelmäßige Einkünfte beziehen.
(4):: Schiedsgerichtswahlen finden alle vier Jahre statt. Das Schiedsgericht bleibt bis zur abgeschlossenen Wahl eines neuen Schiedsgerichts im Amt.
(5):: Eine in ein Schiedsgericht gewählte Person kann durch Erklärung an das Gericht ihr Amt beenden. Scheidet eine in ein Schiedsgericht gewählte Person aus diesem aus, so rückt für diese die in der Rangfolge nächste Ersatzpersonen dauerhaft nach.
(6):: Steht beim Ausscheiden einer in ein Schiedsgericht gewählten Person keine Ersatzperson mehr zur Verfügung, so muss die unbesetzte Position durch Nachwahl besetzt werden. Ebenso können Ersatzpersonen nachgewählt werden. Die ursprüngliche Zahl an gewählten Personen im Schiedsgericht und Ersatzpersonen darf dabei jedoch nicht überschritten werden. Nachgewählte Personen schließen sich in der Rangfolge an noch vorhandene Ersatzpersonen an. Nachwahlen gelten nur für den Rest der Amtszeit.
(7):: Bei tatsächlicher und/sowie angekündigter Nichterreichbarkeit eines Mitglieds des Schiedsgerichts über einen Zeitraum von mindestens zwei Wochen können die Verfahrensbeteiligten und die übrigen Mitglieder des Schiedsgerichts beantragen, das nicht erreichbare Mitglied für abwesend zu erklären. Das Verfahren und die Folgen sind dieselben wie für einen Befangenheitsantrag. Ein wegen Abwesenheit ersetztes Mitglied des Schiedsgerichts bleibt ersetzt, wenn es wieder erreichbar wird. Konnte ein für abwesend erklärtes Mitglied des Schiedsgerichts nicht ersetzt werden, so wird es als Mitglied des Schiedsgerichts wiedereingesetzt, wenn es wieder erreichbar wird.
(8):: Reduziert sich die Zusammensetzung des Schiedsgerichts in einem Verfahren auf ein einziges Mitglied oder kommt bei einer Abstimmung keine Mehrheit zustande, so erklärt sich das Schiedsgericht in Bezug auf dieses Verfahren für handlungsunfähig und unterrichtet darüber umgehend die Verfahrensbeteiligten.

== § 4 Befangenheit

(1):: In ein Schiedsgericht gewählte Personen können sich selbst für befangen erklären und ihre Mitwirkung am Verfahren ablehnen.
(2):: Die Verfahrensbeteiligten können beantragen, einzelne in ein Schiedsgericht gewählte Personen wegen der Besorgnis der Befangenheit vom Verfahren auszuschließen. Das Gesuch muss unmittelbar nach Bekanntwerden des Ablehnungsgrundes gestellt werden. Eine nachträgliche Geltendmachung des Ablehnungsgrundes ist nicht mehr möglich.
(3):: Die betroffene, in ein Schiedsgericht gewählte Person, kann schriftlich zum Befangenheitsantrag Stellung nehmen.
(4):: Über das Ablehnungsgesuch verhandeln die übrigen in ein Schiedsgericht gewählten Personen unter Einsatz einer Ersatzperson. Wird die Befangenheit des Mitglieds festgestellt, scheidet dieses beim weiteren Verfahren aus. Fällt eine in ein Schiedsgericht gewählte Person aufgrund von Befangenheit aus, so tritt für das Verfahren die nach der Rangfolge nächste Ersatzperson ein.

== § 5 Verbot der Doppelbefassung

(1):: Insofern sich Gebietsuntergliederungen gründen, gelten deren Schiedsgerichte als Vorinstanz der Landesschiedsgerichtsbarkeit.
(2):: Eine in ein Schiedsgericht gewählte Person, die bereits in einer Vorinstanz richtend mit der Angelegenheit befasst war, ist von der Mitwirkung ausgeschlossen. In diesem Fall tritt die nächste vorgesehene Ersatzperson ein.

== § 6 Zuständigkeit

(1):: Zuständig ist generell das Gericht der niedrigsten Ordnung.
(2):: Die örtliche Zuständigkeit richtet sich nach der Zugehörigkeit der Gebietsuntergliederung der Person, die sich zum Zeitpunkt der Anrufung gegen eine Maßnahme wehrt.
(3):: Handelt es sich bei der Person, die sich gegen eine Maßnahme wehrt, um ein Organ des Landesverbandes, so ist ausschließlich das Landesschiedsgericht zuständig.
(4):: Für Parteiausschlussverfahren und Einsprüche gegen Ordnungsmaßnahmen ist erstinstanzlich das Schiedsgericht der eigenen Gebietsuntergliederung zuständig.
(5):: Bei Handlungsunfähigkeit oder Nicht-Bestehen des zuständigen Gerichts verweist das nächsthöhere Gericht den Fall an ein anderes, der Eingangsinstanz gleichrangiges, Schiedsgericht oder kann den Fall selbst behandeln.

== § 7 Anträge

(1):: Antragsberechtigt ist jedes Parteimitglied, sofern es in der Sache unmittelbar betroffen ist, alle Parteiorgane sowie 1/10 der stimmberechtigten Teilnehmenden einer Versammlung, sofern eine Wahl oder Entscheidung der Versammlung angefochten wird. Anträge auf Parteiausschlussverfahren können nur von Gebietsorganen gestellt werden.
(2):: Jeder Antrag bedarf der Schriftform und muss begründet werden.
(3):: Die Anrufung des Schiedsgerichts muss binnen zwei Monaten nach Bekanntwerden der Rechtsverletzung erfolgen. Ein Einspruch gegen eine Ordnungsmaßnahme muss spätestens am 14. Tag nach Mitteilung des Beschlusses erhoben werden. Ein Antrag auf Parteiausschluss soll in einem angemessenen Zeitraum seit Bekanntwerden des entscheidenden Vorfalls gestellt werden. Wird ein Schlichtungsversuch durchgeführt, so wird der Ablauf der Frist für die Dauer des Schlichtungsversuchs gehemmt.

== § 8 Schlichtung

(1):: Eine Anrufung des Schiedsgerichts erfordert in der Regel einen vorhergehenden Schlichtungsversuch.
(2):: Der Schlichtungsversuch wird von den Parteien in eigener Verantwortung ohne Mitwirkung der Gerichte durchgeführt. Dazu sollen sich die Parteien auf eine Schlichtungsperson einigen. Ein Schlichtungsversuch gilt spätestens nach erfolglosem Ablauf von drei Monaten nach dessen Beginn als gescheitert. Bei Anrufung des Schiedsgerichts vor Ablauf dieser Frist muss der Antrag das Scheitern der Schlichtung begründen.
(3):: Ein Schlichtungsversuch ist nicht erforderlich bei Eilbedürftigkeit des Verfahrens, der Aussichtslosigkeit einer Schlichtung, Parteiausschlussverfahren, bei Einsprüchen gegen Ordnungsmaßnahmen, sowie bei einer Berufung.

== § 9 Eröffnung

(1):: Nach Feststellung der Zulässigkeit des Antrags eröffnet das zuständige Schiedsgericht das Verfahren mit einem Schreiben an die Verfahrensbeteiligten. In diesem ist die weitere Verfahrensweise bekannt zu geben.
(2):: Der Antrag ist zulässig, wenn das Schiedsgericht zuständig, die Antrag stellende Person antragsbefugt ist und die Form und Frist gewahrt worden sind. Über die Eröffnung ist in der Regel spätestens zwei Wochen nach Eingang des Antrags beim Schiedsgericht zu entscheiden. Im Fall der Eröffnung wählen die in das Schiedsgericht gewählten Personen aus ihrer Mitte eine berichterstattende Person für das Verfahren.
(3):: Erweist sich der Antrag als unzulässig, ist er zu abzuweisen. Die Gründe hierfür sind der antragstellenden Person schriftlich mitzuteilen; dabei ist auf die Möglichkeit von Rechtsmitteln hinzuweisen.

== § 10 Verfahren

(1):: Grundsätzlich fällt das Gericht seine Entscheidungen im mündlichen Verfahren. Nur in Ausnahmefällen kann das Gericht eine schriftliche oder fernmündliche Anhörung anordnen, wenn es zur rechtlichen und tatsächlichen Klärung geboten scheint.
(2):: Den Entscheidungen darf nur zugrunde gelegt werden, was allen Verfahrensbeteiligten bekannt ist und wozu sie Stellung nehmen konnten.
(3):: Bei mündlichen und fernmündlichen Entscheidungen bestimmt das Schiedsgericht Ort und Zeit der Verhandlung.
(4):: Alle Parteimitglieder können dem Verfahren beiwohnen. Die Termine dafür werden rechtzeitig bekannt gegeben.

== § 11 Einstweilige Verfügung

(1):: Das Schiedsgericht kann auf Antrag eine einstweilige Anordnung in Bezug auf den Verfahrensgegenstand erlassen. Ausgenommen sind Parteiausschlussverfahren.
(2):: Die Anordnung ergeht nach einer Anhörung und in dringenden Fällen allein durch die vorsitzende Person im Schiedsgericht.
(3):: Gegen eine solche Entscheidung kann die betroffene Person binnen zwei Wochen nach Zustellung der Anordnung Rechtsmittel einlegen. Die betroffene Person ist in dem Beschluss über diese Möglichkeit zu belehren.

== § 12 Urteil

(1):: Das Urteil enthält eine Sachverhaltsdarstellung und eine Begründung mit Würdigung der Sach- und Rechtslage. Die Urteilsfindung unterliegt dem Beschleunigungsgrundsatz. Entschieden wird in nicht-öffentlicher Beratung des Schiedsgerichts, das Urteil wird mit einfacher Mehrheit gefällt. Enthaltungen sind nicht zulässig. Das Abstimmungsverhalten der in das Schiedsgericht gewählten Personen wird nicht festgehalten.
(2):: Ist gegen das Urteil Berufung möglich, so ist diesem eine Rechtsbehelfsbelehrung beizufügen.
(3):: Die Verfahrensbeteiligten erhalten eine Ausfertigung des Urteils in Textform.
(4):: Das Schiedsgericht bewahrt eine schriftliche, von allen beteiligten in das Schiedsgericht gewählten Personen unterschriebene Ausfertigung des Urteils auf.
(5):: Alle Beschlüsse der Schiedsgerichtskommission sind in anonymisierter Form auf der Homepage der Partei zu veröffentlichen.

== § 13 Berufung

(1):: Gegen erstinstanzliche Urteile steht allen Verfahrensbeteiligten die Berufung zu.
(2):: Die Berufung ist binnen 14 Tagen beim Schiedsgericht der ggf. nächsthöheren Ordnung einzureichen und zu begründen. Der Berufungsschrift ist die angefochtene Entscheidung samt erstinstanzlichem Aktenzeichen beizufügen. Maßgeblich für den Lauf der Berufungsfrist ist die Zustellung des Urteils inklusive Rechtsmittelbelehrung.

== § 14 Kosten

(1):: Das Schiedsgerichtsverfahren ist kostenfrei. Jede am Verfahren beteiligte Person trägt ihre eigenen Auslagen für die Führung des Verfahrens selbst.
(2):: In das Schiedsgericht gewählte Personen erhalten für ihre Tätigkeit keine Entschädigung. Die notwendigen Auslagen, insbesondere Reisekosten, trägt die jeweilige Ebene der Partei.

== § 15 Schlussbestimmungen

(1):: In Abstimmung mit der Berliner Schriftgutaufbewahrungsverordnung vom 16. April 2010 sind Akten bis zu 30 Jahre nach Abschluss des Verfahrens zu verwahren.
(2):: Die Schiedsgerichtskommissionen sind gegenüber dem jeweiligen Parteitag berichtspflichtig.
(3):: Nach Abschluss des Verfahrens kann jedes Parteimitglied Akteneinsicht beantragen. Eine Antragsbefugnis ist nicht erforderlich. Die Akten können anonymisiert werden.
