= Unvereinbarkeitsrichtlinie von radikal:klima

Beschlossen am 9. August 2020

== Präambel

radikal:klima tritt jeder Form von Fremdenfeindlichkeit und Diskriminierung insbesondere aufgrund von Herkunft, Geschlecht, Glauben, körperlicher Verfassung, äußerer Merkmale und sexueller Orientierung entgegen. Unsoziale, rassistische, antisemitische, gewaltvolle, terroristische, verfassungsfeindliche, behindertenfeindliche und totalitäre politische Positionen sowie Ziele sind nicht mit unseren Werten vereinbar. Eine Zusammenarbeit mit Organisationen und Personen, die solche Positionen vertreten oder Ziele verfolgen, ist für radikal:klima daher ausgeschlossen. Verstöße gegen diese Unvereinbarkeitsregelung stellen parteischädigendes Verhalten dar und rechtfertigen ein Ausschlussverfahren aus radikal:klima.

== Mitgliedschaft

Die Mitgliedschaft in anderen Parteien ist nur unter Berücksichtigung von § 2 Absatz 3 und 4 der Satzung möglich. Mitglieder von radikal:klima können nicht gleichzeitig Mitglied bei einer Organisation sein, die sich gegen die Grundsätze der Partei, gegen die Menschenrechte oder gegen eine demokratische, pluralistische Gesellschaft richtet oder Ziele verfolgt, die gegen diese Grundsätze verstoßen sowie die Existenz der hauptsächlich durch den Menschen verursachten Klimakrise anzweifeln. Darunter fallen insbesondere, aber nicht ausschließlich:

=== Parteien

* Alternative für Deutschland -- AfD
* Nationaldemokratische Partei Deutschlands -- NPD
* Deutsche Mitte
* DIE RECHTE
* Pro-Parteien (pro NRW, pro Deutschland etc.)
* Die Republikaner
* Der III. Weg
* Bündnis für Innovation und Gerechtigkeit (BIG)
* Marxistisch-Leninistische Partei Deutschlands -- MLPD
* Widerstand 2020

=== Organisationen

* Burschenschaften, die im Dachverband Deutsche Burschenschaft organisiert sind
* Identitäre Bewegung
* Pro-Bewegung
* BDS (Boycott, Divestment and Sanctions)
* REBELL
* Scientology

Die Mitgliedschaft in diesen Parteien und Organisationen ist mit der Mitgliedschaft bei radikal:klima unvereinbar. Gemäß § 4 Absatz 4 Buchstabe e der Satzung verhält sich parteischädigend, wer einer Organisation angehört oder eine solche fördert, deren Ziele nach dem sachlich gerechtfertigten Verständnis der Partei die gleichzeitige Verfolgung der Ziele und Grundsätze der Partei ausschließen, und dadurch die Glaubwürdigkeit und überzeugungskraft der Partei beeinträchtigt. Dazu gehören insbesondere auch die oben aufgeführten Organisationen.

== Durchsetzung der Regeln in allen Angeboten des Landes

Die Angebote der Landespartei stehen nur Personen offen, die ebenfalls diese Unvereinbarkeitsregelungen beachten. Die jeweiligen betreibenden Teams und Mitglieder sind angehalten, diese durchzusetzen und bei Nicht-Einhalten den Vorstand zu informieren.

== Zusammenarbeit mit Organisationen

Die Partei radikal:klima arbeitet mit den oben genannten Organisationen nicht zusammen, sondern distanziert sich klar von ihren Zielen. Offiziell im Namen der Partei sprechende Personen von radikal:klima, die mit diesen Organisationen zusammenarbeiten, beeinträchtigen dadurch die Glaubwürdigkeit und überzeugungskraft der Partei und verhalten sich damit gemäß § 4 Absatz 4 Buchstabe e der Satzung parteischädigend.

Eine Zusammenarbeit beinhaltet insbesondere die öffentliche Befürwortung von und Kooperation mit o.g. Organisationen und Parteien bei der Erreichung ihrer politischen Ziele; z.B. gemeinsame Gesetzesinitiativen, gemeinsame Veranstaltungen, Bildung gemeinsamer Fraktionen, Zählgemeinschaften und Abgeordneten- oder Verordneten-Gruppen in Parlamenten und anderen Vertretungskörperschaften.

Die Entscheidung über eine Teilnahme an Veranstaltungen und Kampagnen, zu denen eine ausgeschlossenen Partei / Organisation ebenfalls eingeladen ist, trifft der Vorstand. Bei Unsicherheit sollte die Zusammenarbeit mit dem Vorstand besprochen werden. Bedenken über eine Zusammenarbeit können per E-Mail an Mail-Adresse geschickt werden.

Die Gebietsuntergliederungen von radikal:klima sind verpflichtet, sich entsprechend zu verhalten.
